[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_DRAWER = "false"
  NEXT_DISABLE_NETLIFY_DRAWER = "true"

[context.production.environment]
  NETLIFY_DRAWER = "false"

[context.deploy-preview.environment]
  NETLIFY_DRAWER = "false"
